---
title: "Impact du microplastique sur les communautés microbiennes"
author: "Irma Gaziaux, Lila Franchin, Arthur Miroux, Kelly Fodom"
format:
  pdf:
    documentclass: report
    toc: true
editor: visual
lang: fr
bibliography: references.bib
---

<!--# Un rapport est différent d'un carnet de notes. Il ne s'agit donc pas de faire du copier-coller d'un document vers l'autre. Un rapport de synthèse doit être compréhensible sans devoir lire le carnet de notes. Le rapport de synthèse doit être  rédigé avec un style et une présentation adéquats. -->

## Introduction

<!--% Rédigez l'introduction de ce rapport en 5-6 phrases.-->

Dans cette analyse statistique, nous étudions l'effet des microplastiques sur la communauté microbienne marine.. Les microplastiques peuvent avoir un effet négatif sur plusieurs paramètres comme la croissance, le contenu en chlorophylle, l'activité photosynthétique,...(Raju, 2022) Ici nous étudions l'effet des microplastiques sur la biomasse, la proportion en HNA/LNA, la concentration en ammonium et le taux de chlorophylle et l'absence ou la présence de certains microplastiques de différents types

<!--% Rédigez le but de ce rapport en 2 phrases.-->

Le but de ce rapport est d'évaluer l’impact des micro-plastiques et de facteurs abiotiques (température, ammonium...) sur les populations phytoplanctoniques et bactériennes. Cette population est à la base de la chaîne trophique marine d’où l'importance de cet étude.

## Matériel et méthodes

<!--% Cette section doit comprendre deux parties. La première partie doit expliciter les données employées et la seconde traiter des analyses réalisées et des logiciels employés.-->

Les données de cette étude proviennent du dépot Zenodo de @Montoya2023 . Les données comportent différentes variables telles que les concentrations de microplastique et d'ammonium. Pour évaluer l'impact sur les communautés microbiennes, différentes variables sont utilisées telles que la concentration d'acides nucléiques chez les bactéries, la masse du phytoplancton et l'efficacité de la photosynthèse.

Le logiciel utilisé est R (version 4.4.1) (<https://www.r-project.org)> (`r R.version.string`). plus précisément, le package {modelit} version `r packageVersion("modelit")` dans la [SciViews Box 2025](https://www.sciviews.org/software/svbox/). [Saturn Cloud](https://saturncloud.io) (Linux Ubuntu 22.04). Ce package est utilisé afin d'exécuter le code et compiler la version finale de ce bloc-notes. Le jeu de données est remanié (documenté dans le fichier `R/import.R`).

## Résultats

<!--% Présentez les deux modèles les plus pertinents que vous avez sélectionnés. Structurez la section en deux parties avec deux titres de niveau trois.-->

## Discussion et Conclusion

<!--% En tenant compte du but de votre carnet de notes et de vos résultats, discutez de résultats et proposez des conclusions à votre analyse en 5 à 10 phrases. -->

## Bibliographie
